version: '3.8'
services:
  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: postgres:latest
    networks:
      - nesjs-network
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB_PREFIX}_${POSTGRES_DB_NAME}
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-app
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - nesjs-network
    restart: unless-stopped

networks:
  nesjs-network:
